# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.2"

gem "jekyll-paginate", "~> 1.1"

gem "sdbm", "~> 1.0"

gem "webrick", "~> 1.7"

gem "net-telnet", "~> 0.2.0"

gem "xmlrpc", "~> 0.3.2"

gem "s3_website", "~> 3.4"
